import Head from 'next/head'
import TopComponent from '../components/TopComponent'
import FeaturesComponent from '../components/FeaturesComponent'
import ContactComponent from '../components/ContactComponent'

export default function Home() {
  return (
    <div className='body' >
      <Head>
        <title>Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <TopComponent/>
        <FeaturesComponent/>
        <ContactComponent/>
      </main>
    </div>
  )
}
